Repository internxt/drive-server, pull requests merged in 2023-08, with the labels that each got.

#410 [PB-755]: bugfix/Send to client correct http error and no generic one
  src/app/routes/auth.ts
Labels: bug

#412 [_]: feature/Changed error message when email or password is wrong
  src/app/routes/auth.ts
  src/app/services/user.js
  tests/controllers/auth.test.ts
  tests/e2e/e2e-spec.ts
Labels: enhancement

#411 [PB-813] fix: return http code 409 when trying to rename a file with an exists
  src/app/routes/storage.ts
  src/app/services/errors/FileWithNameAlreadyExistsError.ts
  src/app/services/errors/FolderWithNameAlreadyExistsError.ts
  src/app/services/files.js
  src/app/services/folder.js
Labels: bug

#413 [PB-118]: Feat/middleware private sharing
  src/app/middleware/resource-sharing.middleware.ts
  src/app/models/index.ts
  src/app/models/permissions.ts
  src/app/models/privateSharingFolder.ts
  src/app/models/privateSharingFolderRole.ts
  src/app/models/roles.ts
  src/app/routes/storage.ts
  src/app/services/privateSharing.js
  src/lib/performance/network.ts
Labels: enhancement, mod: private-sharing

#415 [PB-118]: feat/advanced sharing
  src/app/models/index.ts
  src/app/models/permissions.ts
  src/app/models/roles.ts
  src/app/models/sharingInvites.ts
  src/app/models/sharingRoles.ts
  src/app/models/sharings.ts
  src/app/services/privateSharing.js
Labels: enhancement, mod: private-sharing
