Repository internxt/drive-server, pull requests merged in 2024-04, with the labels that each got.

#434 [_]:(fix) Detect if backups device exists and is not deleted
  src/app/services/backups.js
Labels: enhancement, ready-for-preview

#435 [_]: bugfix/Added condition to get only existing files and folders
  src/app/services/folder.js
Labels: bug

#436 [_]:(fix) Add log to view device update payload for backups
  src/app/routes/backup.js
Labels: ready-for-preview
